server:
  port: 8088

logging:
  level:
    org:
      springframwork: DEBUG

spring:
  message:
    basename: messages
  security:
    user:
      name: username
      password: passw0rd

management:
  endpoints:
    web:
      exposure:
        include: "*"
